print message if clipboard-cli is not installed

diff --git a/util/fzf_actions/__gshow_actions b/util/fzf_actions/__gshow_actions
--- a/util/fzf_actions/__gshow_actions
+++ b/util/fzf_actions/__gshow_actions
@@ -7,6 +7,15 @@ source "$__CUSTOM_CONSOLE_UTIL"/__print_as
 
 function __gshow_actions() {
 
+    if ! command -v clipboard &> /dev/null; then
+        echo
+        __print_as "blue" "clipboard-cli"
+        printf "%s\n\n" " is required to copy the commit SHA to the clipboard."
+        printf "Please install from: "
+        __print_as "blue" "https://github.com/sindresorhus/clipboard-cli"
+        return
+    fi
+
 	local str="${1}"
 	local abbrCommitSHA="$(echo "$str" | grep -E "[0-9a-z]+" -o | head -n 1)"
 	local longCommitSHA="$(git rev-parse "${abbrCommitSHA}")"
